---
- hosts: proxmox
  become: true

  tasks:
  - name: Clone cloud-init template
    community.general.proxmox_kvm:
      node: pve1
      vmid: 9000 
      clone: LMDE-Template 
      name: LMDE-Desktop-01
      net: 
        net0: 'virtio=bc:24:11:01:27:05'
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}" 
      api_token_secret: "{{ api_token_secret }}" 
      api_host: 192.168.50.101 # 
      storage: data
      timeout: 90
